numero1 = int(input("Insira o primeiro número inteiro: "))
numero2 = int(input("Insira o segundo número inteiro: "))
print("Você inseriu os números:", numero1, "e", numero2)
soma = (numero1 + numero2)
produto = (numero1 + numero2)
print(f"A soma dos números:{ soma }")